openapi: 3.0.0
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: '1.0'
paths:
  /api/requests:
    get:
      summary: Returns all requests from database
      responses:
        '200':
          description: All requests from database
          content:
            application/json:
              schema:
                type: object
                properties:
                  requests:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        tg_id:
                          type: string
                        request_type:
                          type: string
                        request_description:
                          type: string
                        status_id:
                          type: string
  /api/resources:
    get:
      summary: Returns all resources from database
      responses:
        '200':
          description: All resources from database
          content:
            application/json:
              schema:
                type: object
                properties:
                  resources:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        tg_id:
                          type: string
                        resource_name:
                          type: string
                        resource_description:
                          type: string
                        resource_type:
                          type: string
                        available_quantity:
                          type: integer
  /api/delete_resource:
    post:
      summary: Deletes resource from DataBase
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  /api/delete_request:
    post:
      summary: Deletes request from DataBase
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
components:
  schemas:
    items:
      type: "object"
      properties:
        telegramId:
          type: "string"
          message:
            type: "string"