openapi: 3.0.0
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: '1.0'
paths:
  /api/user-list:
    get:
      summary: Returns all user data from DB
      responses:
        '200':
          description: All user data retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        telegramId:
                          type: string
                        message:
                          type: string
components:
  schemas:
    items:
      type: "object"
      properties:
        telegramId:
          type: "string"
        message:
          type: "string"
