openapi: 3.0.0
info:
  title: Technoscouting API - OpenAPI 3.0
  version: "0.1"


components:
  schemas:
    id:
      type: object
      properties:
        _id:
          type: string
    application:
      type: object
      properties:
        date:
          type: string
        organization:
          type: string
        contactName:
          type: string
        telegramId:
          type: long
        requestText:
          type: string
        status:
          type: string
          enum: ["incoming", "resources search", "resources attached", "in work", "ended", "declined by scout", "declined by client"]
        associatedResources:
          type: array
          items:
            type: string

    applicationWithId:
      allOf:
        - $ref: "#/components/schemas/application"
        - $ref: "#/components/schemas/id"

    resource:
      type: object
      properties:
        date:
          type: string
        organization:
          type: string
        contactName:
          type: string
        telegramId:
          type: long
        competenceField:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        status:
          type: string
          enum: ["in work", "available"] #TODO: тут ещё скорее всего какие-то есть, не придумалось с ходу
        associatedApplications:
          type: array
          items:
            type: string

    resourceWithId:
      allOf:
        - $ref: "#/components/schemas/resource"
        - $ref: "#/components/schemas/id"


    logIn:
      type:
        object
      properties:
        login:
          type: string
        password:
          type: string

    token:
      type:
        object
      properties:
        token:
          type: string
        expiration:
          type: number

    attacher:
      type:
        object
      properties:
        applicationId:
          type: string
        resourceIds:
          type: array
          items:
            type: string
        message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []

paths:
  /api/applications:
    get:
      summary: Returns all applicatons from database
      responses:
        "200":
          description: Successfully returned all applicatons from database
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicationWithId"
        '401':
          description: Authorization error
        '503':
          description: Connection to DataBase error

  /api/resources:
    get:
      summary: Returns all resources from database
      responses:
        "200":
          description: Successfully returned all resources from database
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/resourceWithId"
        '401':
          description: Authorization error
        '503':
          description: Connection to DataBase error

  /api/delete_application:
    post:
      summary: Deletes application from DataBase
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/id"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicationWithId"
        '400':
          description: Invalid arguments were given
        '401':
          description: Authorization error
        "404":
          description: Application with given id was not found
        '503':
          description: Connection to DataBase error

  /api/delete_resource:
    post:
      summary: Deletes resource from DataBase
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/id"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/resourceWithId"
        '400':
          description: Invalid arguments were given
        '401':
          description: Authorization error
        "404":
          description: Resource with given id was not found
        '503':
          description: Connection to DataBase error

  /api/create_application:
    post:
      summary: Create new application and add it to the database
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/application"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicationWithId"
        '400':
          description: Invalid arguments were given
        '401':
          description: Authorization error
        '503':
          description: Connection to DataBase error

  /api/create_resource:
    post:
      summary: Create new resource and add it to the database
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/resource"
      responses:
        "200":
          description: New resource added
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/resourceWithId"
        '400':
          description: Invalid arguments were given
        '401':
          description: Authorization error
        '503':
          description: Connection to DataBase error

  /api/update_application:
    post:
      summary: Update existing application by its _id
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/applicationWithId"
      responses:
        "200":
          description: Application successfully updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicationWithId"
        '400':
          description: Invalid arguments were given
        '401':
          description: Authorization error
        "404":
          description: Application with given id was not found
        '503':
          description: Connection to DataBase error

  /api/update_resource:
    post:
      summary: Update existing resource by its _id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/resourceWithId"
      responses:
        "200":
          description: Resource successfully updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/resourceWithId"
        '400':
          description: Invalid arguments were given
        '401':
          description: Authorization error
        "404":
          description: Resource with given id was not found
        '503':
          description: Connection to DataBase error

  /api/add_new_admin:
    post:
      summary: Add new admin
      requestBody:
        content:
          application/json:
            schema:
              newAdmin:
                type: object
                properties:
                  login:
                    type: string
                  password:
                    type: string
      responses:
        "200":
          description: New admin added
        '401':
          description: Authorization error
        '503':
          description: Connection to DataBase error

  /api/log-in:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/logIn"
      responses:
        "200":
          description: Successfully logged-in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/token"
        '401':
          description: Authorization Error
        '503':
          description: Connection to DataBase error
  /api/assign_resources:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/attacher"
      responses:
        "200":
          description: Resources were assigned
        '401':
          description: Authorization error
        "404":
          description: Application or resource with given id was not found
        '503':
          description: Connection to DataBase error

