services:

# TODO: add mongo
#  mongo:
#    image: mongo:latest
#    container_name: calculator_db
#    environment:
#     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#      MONGO_INITDB_DATABASE: ${MONGO_DB}
#    volumes:
#      - scouting_data:/data/db
#    ports:
#      - "${MONGO_PORT}:27017"

# TODO: add backend
#  backend:
#    build:
#      context: ./backEnd
#      dockerfile: Dockerfile
#    container_name: scouting_back
#    environment:
#      POSTGRES_HOST: postgres
#      POSTGRES_PORT: 5432
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    depends_on:
#      - mongo

  frontend:
    build: 
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: scouting_frontend
    ports:
      - "3000:3000"

  nginx:
    container_name: scouting_nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      # - backend
      - frontend
volumes:
  calculator_data: