name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request_target:
    branches: [ main ]
    paths:
      - 'backend/**'

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Run KtLint with Reviewdog
      uses: ScaCap/action-ktlint@v1.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        level: error

    - name: Upload KtLint Report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ktlint-report
        path: backend/build/reports/ktlint/

    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew build

    - name: Run tests
      run: |
        cd backend
        ./gradlew test
