name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Check formatting with Spotless
      run: |
        cd backend
        ./gradlew spotlessCheck

    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew build

    - name: Run tests
      run: |
        cd backend
        ./gradlew test

