name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      mongodb:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: test_user
          MONGO_INITDB_ROOT_PASSWORD: test_password
          MONGO_INITDB_DATABASE: test_db
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        cd backend
        docker build -t scouting-backend .

    - name: Run tests
      env:
        MONGODB_HOST: localhost
        MONGODB_PORT: 27017
        MONGODB_USERNAME: test_user
        MONGODB_PASSWORD: test_password
        MONGODB_DBNAME: test_db
      run: |
        docker run \
          -e MONGODB_HOST \
          -e MONGODB_PORT \
          -e MONGODB_USERNAME \
          -e MONGODB_PASSWORD \
          -e MONGODB_DBNAME \
          --network host \
          scouting-backend \
          ./gradlew test