name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Check formatting 
      run: |
        cd backend
        ./gradlew ktlintCheck

    - name: Upload KtLint Report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: ktlint-report
        path: backend/build/reports/ktlint/

    - name: Reviewdog - KtLint
      if: failure()
      uses: reviewdog/action-ktlint@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        level: error
        ktlint_flags: '--reporter=plain'
        fail_on_error: true
        
    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew build

    - name: Run tests
      run: |
        cd backend
        ./gradlew test
