name: Deploy Application

on:
  push:
    branches:
      # - main
      - 32-cd-add-deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via rsync & ssh
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          ARGS: -rlgoDzvc -i --delete
          SSH_CMD_ARGS: -o ServerAliveInterval=1500
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_SSH_USER }}
          TARGET: /home/${{ secrets.DEPLOY_SSH_USER }}/app
          EXCLUDE: /.git/, /**/.env
          SCRIPT_BEFORE_REQUIRED: true
          SCRIPT_BEFORE: |
            cd /home/${{ secrets.DEPLOY_SSH_USER }}/app
            docker system prune -f
            docker compose down
          SCRIPT_AFTER_REQUIRED: true
          SCRIPT_AFTER: |
            cd /home/${{ secrets.DEPLOY_SSH_USER }}/app
            docker compose up -d --remove-orphans --build
