name: Deploy Application

on:
  push:
    branches:
      # - main
      - 32-cd-add-deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via Docker Compose Remote SSH
        uses: astappiev/docker-compose-remote-action@v1
        with:
          ssh_user: ${{ secrets.DEPLOY_SSH_USER }}
          ssh_host: ${{ secrets.DEPLOY_SSH_HOST }}
          ssh_private_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          ssh_host_public_key: ${{ secrets.DEPLOY_SSH_HOST_PUBLIC_KEY }}
          ssh_jump_host: ${{ secrets.DEPLOY_SSH_JUMP_HOST }}
          ssh_jump_public_key: ${{ secrets.DEPLOY_SSH_JUMP_PUBLIC_KEY }}
          docker_use_stack: false
          docker_compose_filename: docker-compose.yml
          docker_args: -d --remove-orphans --build
