name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Run Prettier with Reviewdog
      uses: EPMatt/reviewdog-action-prettier@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        level: error
        workdir: frontend
        prettier_flags: '.'

    - name: Run tests
      run: |
        cd frontend
        npm test
